name = "NamedDimsArrays"
uuid = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"
version = "0.13.7"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionImplementations = "7c7cc465-9c6a-495f-bdd1-f42428e86d0c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"

[weakdeps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
NamedDimsArraysAbstractTreesExt = "AbstractTrees"
NamedDimsArraysBlockArraysExt = "BlockArrays"
NamedDimsArraysMooncakeExt = "Mooncake"

[compat]
AbstractTrees = "0.4.5"
Adapt = "4.1.1"
ArrayLayouts = "1.11"
BlockArrays = "1.3"
Compat = "4.16"
FillArrays = "1.13"
FunctionImplementations = "0.4"
LinearAlgebra = "1.10"
Mooncake = "0.4.202, 0.5"
Random = "1.10"
SimpleTraits = "0.9.4"
TensorAlgebra = "0.6.12"
TupleTools = "1.6"
TypeParameterAccessors = "0.4"
VectorInterface = "0.5.0"
julia = "1.10"
